name: book management system pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]



jobs:
  lint:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
            
      - name: Install Poetry
        run: pip install poetry
        
      - name: Install dependencies
        run: poetry install --no-root
        
      - name: Run Ruff (linter & formatter)
        run: poetry run ruff check .
        
      - name: Run Pylint
        run: poetry run pylint $(git ls-files '*.py')

            